#ifndef _KUMALSYSTEMOP_H
#define _KUMALSYSTEMOP_H

enum KUMA_LSYSTEM_OP {
	KLS_FORWARD,
	KLS_ROTATE_LEFT,
	KLS_ROTATE_RIGHT,
	KLS_ROTATE_LEFT_AND_PUSH,
	KLS_POP_AND_ROTATE_RIGHT
};

#endif // _KUMALSYSTEMOP_H